// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzu52Z4D5UXbaUFZCLDJb0ZzAY3w78IZw',
    appId: '1:463026262223:web:a08b3c45e4cb465e6c27ba',
    messagingSenderId: '463026262223',
    projectId: 'strive-saude-app',
    authDomain: 'strive-saude-app.firebaseapp.com',
    storageBucket: 'strive-saude-app.firebasestorage.app',
    measurementId: 'G-CCQLESCQ25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMrVsGgUbIAuXqtmc4-oXNaqdfKQPXp3M',
    appId: '1:463026262223:android:c1f248a02165f5296c27ba',
    messagingSenderId: '463026262223',
    projectId: 'strive-saude-app',
    storageBucket: 'strive-saude-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWEFywWYzVvYMwEaM3MyoyVHaCGHbYfBQ',
    appId: '1:463026262223:ios:e3ad4439b25e15286c27ba',
    messagingSenderId: '463026262223',
    projectId: 'strive-saude-app',
    storageBucket: 'strive-saude-app.firebasestorage.app',
    androidClientId: '463026262223-ii2qrbmpvotub4c748hmgslq6aft9lho.apps.googleusercontent.com',
    iosClientId: '463026262223-0qb8vrrf7704m1rl4pqtcsajt9mhhd0h.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );

}